---
name: CI - Maven Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: "17"
            distribution: temurin
        - name: Maven Build
          run: mvn clean install -DskipTests=true
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: target
            path: target/
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: "17"
              distribution: temurin
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
              name: target
              path: target/
          - name: Maven Test
            run: mvn test
